AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Car Tech Showcase Application

Resources:
  CarApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CarApiFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: backend/
      Events:
        CarApi:
          Type: Api
          Properties:
            Path: /api/cars
            Method: get
