name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Bandit
      run: pip install bandit

    #- name: Run Bandit (SAST)
      #run: bandit -r backend/ -c security/bandit_config.yaml -f json -o bandit_report.json

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'backend-image:latest'
        format: 'table'

    - name: Build with SAM
      run: sam build

    - name: Deploy with SAM
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name car-tech-showcase \
          --capabilities CAPABILITY_IAM
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.9.0
      with:
        target: 'http://localhost:5000'
        config_file: security/zap_config.yaml
